### ISSUE TITLE
DonutCraft ToDo

### ISSUE THREAD

**Issue by DoughnutDev** [DoughnutServers/DonutCraftATL#40]
- [ ] EFLN Recipe Change
- [ ]  /ftb admin doesn't work
- [ ] Oregen changes with ORE and BASE
- [ ] New Recipe Ideas
